version: "0.4.5"

messages:
  responses:
    inline_content_title: "ğŸ† Ğ£Ğ·Ğ½Ğ°Ñ‚ÑŒ ÑĞ²Ğ¾Ğ¹ Ñ€Ğ°Ğ·Ğ¼ĞµÑ€"
    inline_content_description: "Ğ Ğ°Ğ·Ğ¼ĞµÑ€ Ğ²Ğ°ÑˆĞµĞ³Ğ¾ ÑˆÑ‚ÑƒÑ†ĞµÑ€Ğ° ÑĞµĞ³Ğ¾Ğ´Ğ½Ñ"
    no_stats: "ĞŸÑƒÑÑ‚Ğ¾"
  errors:
    unknown_command: "ĞšĞ¾Ğ¼Ğ°Ğ½Ğ´Ğ° Ğ½Ğµ Ğ½Ğ°Ğ¹Ğ´ĞµĞ½Ğ° ğŸ˜³ğŸ˜³ğŸ˜³"